version: "2"
run:
  tests: true
linters:
  enable:
    - copyloopvar
    - dupl
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - predeclared
    - revive
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    godot:
      scope: all
      period: false
    revive:
      rules:
        - name: dot-imports
        - name: exported
        - name: var-naming
        - name: receiver-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ^tools/docgen/.*\.go$
      - ^internal/command/si\.go$
      - ^internal.command/si/*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/tfctl/tfctl
  exclusions:
    generated: lax
    paths:
      - ^tools/docgen/.*\.go$
      - ^internal/command/si\.go$
      - ^internal.command/si/*
      - third_party$
      - builtin$
      - examples$
