.TH tfctl 1 "May 25, 2026" "tfctl v1.2.3" "tfctl"
.SH NAME
tfctl \- Terraform Control
.SH USAGE
tfctl [global options] [command [command options]]
.SH COMMANDS

.TP
\fBmq\fR
module registry query

.TP
\fBoq\fR
organization query

.TP
\fBpq\fR
project query

.TP
\fBps\fR
plan summary

.TP
\fBrq\fR
run query

.TP
\fBsq\fR
state query

.TP
\fBsvq\fR
state version query

.TP
\fBwq\fR
workspace query

.SH GLOBAL OPTIONS

.TP
\fB--help,\fR
show tfctl command help


.TP
\fB--version, -v\fR
tfctl version info

