.TH tfctl 1 "May 17, 2026" "tfctl v1.2.2" "tfctl"
.SH NAME
tfctl \- Terraform Control
.SH USAGE
tfctl [global options] [command [command options]]
.SH COMMANDS

.TP
\fBmq\fR
module registry query

.TP
\fBoq\fR
organization query

.TP
\fBpq\fR
project query

.TP
\fBps\fR
plan summary

.TP
\fBrq\fR
run query

.TP
\fBsq\fR
state query

.TP
\fBsvq\fR
state version query

.TP
\fBwq\fR
workspace query

.TP
\fBhelp, h\fR
Shows a list of commands or help for one command

.SH GLOBAL OPTIONS

.TP
\fB--version, -v\fR
tfctl version info


.TP
\fB--help, -h\fR
show help

